In [1]:
import numpy as np

In [2]:
a = [10,11,12,13,14,15]

In [3]:
n_a = np.array(a)

In [4]:
n_a

array([10, 11, 12, 13, 14, 15])

In [5]:
n_a[0]

10

In [14]:
n_a[1]
last_index = len(n_a) -1
n_a[last_index]
n_a[-1]

15

In [15]:
n_a[-2]

14

In [30]:
n_a[-2:]

array([14, 15])

In [31]:
n_a[0:3]

array([10, 11, 12])

In [32]:
n_a[3:6]

array([13, 14, 15])

In [34]:
n_a[1:-1]

array([11, 12, 13, 14])

In [39]:
n_b = [100,101,102,103,104,105]

In [40]:
n_c = np.concatenate([n_a,n_b])
n_c

array([ 10,  11,  12,  13,  14,  15, 100, 101, 102, 103, 104, 105])

In [42]:
np.average(n_b)

102.5

In [61]:
n_random = np.random.randint(0,10,10)
n_random

array([2, 1, 9, 5, 9, 7, 4, 6, 6, 1])

In [62]:
np.sort(n_random)

array([1, 1, 2, 4, 5, 6, 6, 7, 9, 9])

In [63]:
np.argsort(n_random)

array([1, 9, 0, 6, 3, 7, 8, 5, 2, 4])